theme: just-the-docs
markdown: kramdown
title: "Specmatic"
latest_release: 2.13.2
jms_release: 0.1.0
kafka_release: 0.4.0
db_release: 0.61.8-db
redis_release: 0.9.0
contact_us_url: "https://specmatic.io/contact-us"

spec_cmd: "java -jar /path/to/specmatic.jar"
url: "https://docs.specmatic.io"

aux_links:
  "Specmatic on GitHub":
    - "https://github.com/specmatic/specmatic"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

logo: "/images/specmatic-logo.png"
favicon_ico: /images/favicon/favicon.ico

redirect_from:
  json: false

exclude:
  - README.md
  - Rakefile
  - CNAME

mermaid:
  path: '/js/mermaid-11.6.0.min.js'
  config:

enable_copy_code_button: true
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/specmatic/docs.specmatic.io"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

compress_html:
  ignore:
    envs: all
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

callouts:
  important:
    title: Important
    color: yellow
