openapi: 3.0.1
info:
  title: Redis Contract
  version: "1"
paths:
  /redis:
    post:
      summary: Redis stub
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Redis_RequestBody'
      responses:
        "200":
          description: New scenario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Redis_ResponseBody'
components:
  schemas:
    ListOfValues:
      type: array
      items:
        $ref: '#/components/schemas/Value'
    Value:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
        value:
          type: string
    Redis_RequestBody:
      required:
        - operation
        - params
      properties:
        operation:
          type: string
        params:
          type: array
          items:
            type: string
    Redis_ResponseBody:
      required:
        - type
        - value
      properties:
        type:
          type: string
          enum:
            - string
            - long
            - array
        value:
          oneOf:
            - $ref: '#/components/schemas/ListOfValues'
            - type: string
