openapi: 3.0.1
info:
  title: New Feature
  version: "1"
paths:
  /triple/{value}:
    get:
      summary: three times
      parameters:
        - name: value
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: three times
          content:
            application/json:
              schema:
                type: number