name: Lint, Validate Examples and Check Backward Compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts'

      - name: Install Spectral Linter
        run: npm install -g @stoplight/spectral-cli

      - name: Run Spectral linter
        run: spectral lint **/*.yaml

      - name: Validate OpenAPI examples
        run: |
          docker run -v "$(pwd):/usr/src/app" \
            specmatic/specmatic \
            examples validate --specs-dir=io/specmatic/examples/store/openapi

      - name: Run OpenAPI backward compatibility check
        run: |
          docker run -v "$(pwd):/usr/src/app" \
            --user $(id -u):$(id -g) \
            specmatic/specmatic \
            backward-compatibility-check --base-branch=origin/main
