name: Provider and Consumer CI Build with CTRF Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CTRF_REPORT_PATH: './build/reports/specmatic/test/ctrf/*.json'
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Save Specmatic license
        run: |
          mkdir -p ~/.specmatic
          echo "${{ secrets.SPECMATIC_LICENSE_KEY }}" > ~/.specmatic/specmatic-license.txt

      - name: Run Specmatic stub to virtualize the Order API service
        run: |
          docker run -d \
            -v ${{ github.workspace }}/specmatic.yaml:/usr/src/app/specmatic.yaml \
            -v ${{ github.workspace }}/build/reports/specmatic:/usr/src/app/build/reports/specmatic \
            -p 9000:9000 \
            specmatic/enterprise stub

          # Wait for the stub to be ready
          sleep 10

      - name: Start Spring Boot application
        run: ./gradlew bootRun &

      - name: Wait for application to start
        run: sleep 30

      - name: Contract Test BFF service using Specmatic
        run: |
          docker run \
            -v ${{ github.workspace }}/specmatic.yaml:/usr/src/app/specmatic.yaml \
            -v ${{ github.workspace }}/build/reports/specmatic:/usr/src/app/build/reports/specmatic \
            --network=host \
             specmatic/enterprise test \
            --port=8080 \
            --host=localhost

      - name: Upload CTRF Report
        uses: actions/upload-artifact@v6
        if: always() # Run even if tests fail
        with:
          name: ctrf-report
          path: ${{ env.CTRF_REPORT_PATH }}
          retention-days: 5

      - name: Publish Test Results in CTRF format
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: ${{ env.CTRF_REPORT_PATH }}

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v6
        with:
          name: specmatic-html-report
          path: ./build/reports/specmatic/html