openapi: 3.0.0
info:
  title: PhoneBook API
  version: '1.0'
paths:
  /search:
    post:
      summary: Search By Name
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: The name to be searched for
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - number
                  properties:
                    name:
                      type: string
                      description: The name of the person
                    number:
                      type: string
                      description: The phone number of the person