name: Manual Update Document Version

on: 
 workflow_dispatch:
    inputs:
        SPECMATIC_LATEST_RELEASE_VERSION:
            description: 'Specmatic Latest Release Version e.g. v1.0.0'
            required: true
            type: string

env:
    SPECMATIC_LATEST_RELEASE_VERSION: ${{ github.event.inputs.SPECMATIC_LATEST_RELEASE_VERSION }}
   
jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        repository: znsio/specmatic-documentation
        fetch-depth: 0
        ref: master
        token: ${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_TOKEN }}
        path: documentation
    - name: Update version in _config.yaml
      run: |
        sed -i "s/latest_release: .*/latest_release: $SPECMATIC_LATEST_RELEASE_VERSION/" documentation/_config.yaml
    - name: Commit and push    
      run: |
        git config --global user.name '${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_USER_NAME }}'
        git config --global user.email '${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_USER_EMAIL }}'
        git add .
        git commit -m "Updated Specmatic Documentation Version To $SPECMATIC_LATEST_RELEASE_VERSION"
        git push
      working-directory: documentation