name: Bump tool versions

on:
  workflow_dispatch:
    inputs:
      specmatic-release-test-version:
        description: Specmatic Release Test Version
        required: false
        type: string
        default: ''

      specmatic-core-version:
        description: Specmatic Core Version
        required: false
        type: string
        default: ''

      specmatic-studio-version:
        description: Specmatic Studio Version
        required: false
        type: string
        default: ''

      specmatic-async-version:
        description: Specmatic Async Version
        required: false
        type: string
        default: ''

      specmatic-openapi-version:
        description: Specmatic OpenAPI Version
        required: false
        type: string
        default: ''

jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
    - name: Configure git cli
      run: |
        git config --global user.email "github-service-account@specmatic.io"
        git config --global user.name "Specmatic GitHub Service Account"
    - name: Bump version
      run: |
        if [ -n "${{ github.event.inputs.specmatic-release-test-version }}" ]; then
          echo "Bumping Specmatic Release Test version to ${{ github.event.inputs.specmatic-release-test-version }}"
          sed -i "s/^specmatic-release-test-version: .*/specmatic-release-test-version: ${{ github.event.inputs.specmatic-release-test-version }}/" _config.yml
          git add .
          git commit -m "Updated Specmatic Release Test Version To ${{ github.event.inputs.specmatic-release-test-version }}"
        else
          echo "No Specmatic Release Test version provided, skipping bump."
        fi

        if [ -n "${{ github.event.inputs.specmatic-core-version }}" ]; then
          echo "Bumping Specmatic Core version to ${{ github.event.inputs.specmatic-core-version }}"
          sed -i "s/^specmatic-core-version: .*/specmatic-core-version: ${{ github.event.inputs.specmatic-core-version }}/" _config.yml
          git add .
          git commit -m "Updated Specmatic Core Version To ${{ github.event.inputs.specmatic-core-version }}"
        else
          echo "No Specmatic Core version provided, skipping bump."
        fi

        if [ -n "${{ github.event.inputs.specmatic-studio-version }}" ]; then
          echo "Bumping Specmatic Studio version to ${{ github.event.inputs.specmatic-studio-version }}"
          sed -i "s/^specmatic-studio-version: .*/specmatic-studio-version: ${{ github.event.inputs.specmatic-studio-version }}/" _config.yml
          git add .
          git commit -m "Updated Specmatic Studio Version To ${{ github.event.inputs.specmatic-studio-version }}"
        else
          echo "No Specmatic Studio version provided, skipping bump."
        fi

        if [ -n "${{ github.event.inputs.specmatic-async-version }}" ]; then
          echo "Bumping Specmatic Async version to ${{ github.event.inputs.specmatic-async-version }}"
          sed -i "s/^specmatic-async-version: .*/specmatic-async-version: ${{ github.event.inputs.specmatic-async-version }}/" _config.yml
          git add .
          git commit -m "Updated Specmatic Async Version To ${{ github.event.inputs.specmatic-async-version }}"
        else
          echo "No Specmatic Async version provided, skipping bump."
        fi

        if [ -n "${{ github.event.inputs.specmatic-openapi-version }}" ]; then
          echo "Bumping Specmatic OpenAPI version to ${{ github.event.inputs.specmatic-openapi-version }}"
          sed -i "s/^specmatic-openapi-version: .*/specmatic-openapi-version: ${{ github.event.inputs.specmatic-openapi-version }}/" _config.yml
          git add .
          git commit -m "Updated Specmatic OpenAPI Version To ${{ github.event.inputs.specmatic-openapi-version }}"
        else
          echo "No Specmatic OpenAPI version provided, skipping bump."
        fi

    - name: Git push
      run: git push
