name: Documentation Update

on:
  repository_dispatch:
    types: [specmatic-core-release]

env:
  VERSION: ${{ github.event.client_payload.version }}  
   
jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        repository: znsio/specmatic-documentation
        fetch-depth: 0
        ref: main
        token: ${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_TOKEN }}
        path: documentation
    - name: Set version in environment
      run: echo "VERSION=${VERSION#refs/tags/}" >> $GITHUB_ENV
    - name: Update version in _config.yaml
      run: |
        sed -i "s/latest_release: .*/latest_release: $VERSION/" documentation/_config.yaml
    - name: Commit and push    
      run: |
        git config --global user.name '${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_USER_NAME }}'
        git config --global user.email '${{ secrets.SPECMATIC_CORE_VERSION_UPDATE_USER_EMAIL }}'
        git add .
        git commit -m "Updated Specmatic Documnentation Version To $VERSION"
        git push
      working-directory: documentation