name: Documentation Update

on:
  repository_dispatch:
    types: [specmatic-core-release]
  workflow_dispatch:
    inputs:
        SPECMATIC_LATEST_RELEASE_VERSION_MANUAL:
            description: 'Specmatic Latest Release Version e.g. v1.0.0'
            required: true
            type: string
            default: ''

env:
  SPECMATIC_LATEST_RELEASE_VERSION: ${{ github.event.client_payload.latest-release }}${{ github.event.inputs.SPECMATIC_LATEST_RELEASE_VERSION_MANUAL }}

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: "${{ secrets.SPECMATIC_GITHUB_TOKEN }}"
    - name: Update version in _config.yml
      run: |
        sed -i "s/latest_release: .*/latest_release: $SPECMATIC_LATEST_RELEASE_VERSION/" _config.yml
    - name: Commit and push
      run: |
        git config --global user.email "github-service-account@specmatic.io"
        git config --global user.name "Specmatic GitHub Service Account"
        git add .
        git commit -m "Updated Specmatic Version To $SPECMATIC_LATEST_RELEASE_VERSION"
        git push
